# Theme and plugin settings
remote_theme: daviddarnes/alembic


# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji


favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'


  # 7. Site settings

title: TagChoose - AI Bookmark Manager
logo: "/assets/images/logo.svg" # Site logo, also used in jekyll-seo-tag
description: TagChoose - AI Bookmark Manager
google_analytics: "G-2E7ZVPF2LY"

# 9. Site navigation
navigation_header:
- title: "About #TagChoose"
  url: /
- title: "Technical Details"
  url: /technical-details.html

fonts:
  font_urls:
    - https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Meera+Inimai&display=swap