# Theme and plugin settings
remote_theme: daviddarnes/alembic

# Site settings
title: TagChoose - AI Bookmark Manager
description: TagChoose - AI Bookmark Manager

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji


  # 7. Site settings
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
