# Theme and plugin settings
remote_theme: daviddarnes/alembic


# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji


  # 7. Site settings

title: TagChoose - AI Bookmark Manager
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: TagChoose - AI Bookmark Manager
google_analytics: "G-2E7ZVPF2LY"
